"""Internal interface for the `is_it_slop` package.

This module provides thin Python wrappers around Rust bindings to ensure
excellent IDE support with type hints and documentation.
All core functionality is implemented in Rust for maximum performance.
"""

from __future__ import annotations

from typing import Final, Literal

from ._is_it_slop_rust_bindings import CLASSIFICATION_THRESHOLD as _CLASSIFICATION_THRESHOLD
from ._is_it_slop_rust_bindings import MODEL_VERSION as _MODEL_VERSION
from ._is_it_slop_rust_bindings import PredictionResult as _PredictionResult
from ._is_it_slop_rust_bindings import __version__
from ._is_it_slop_rust_bindings import is_this_slop as _is_this_slop
from ._is_it_slop_rust_bindings import is_this_slop_batch as _is_this_slop_batch

CLASSIFICATION_THRESHOLD: Final[float] = _CLASSIFICATION_THRESHOLD
"""Default classification threshold between 0.0 and 1.0.

If P(AI) >= threshold, the text is classified as AI-generated.
Lower thresholds are more sensitive (classify more as AI), higher thresholds are more conservative (classify more as Human).
This threshold is optimized for overall f1 score based on validation data and is used by default in prediction functions.
"""

MODEL_VERSION: Final[str] = _MODEL_VERSION
"""Version of the underlying ML model used for predictions."""

__all__ = [
    "CLASSIFICATION_THRESHOLD",
    "MODEL_VERSION",
    "Prediction",
    "__version__",
    "is_this_slop",
    "is_this_slop_batch",
    "predict",
    "predict_batch",
]


class Prediction:
    """Result of a prediction containing probabilities and classification.

    This is a thin wrapper around the Rust PredictionResult type, providing
    full type hints and documentation for an excellent IDE experience.

    Attributes:
        human_probability: Probability that the text is human-written (0.0 to 1.0)
        ai_probability: Probability that the text is AI-generated (0.0 to 1.0)
        classification: Classification label ("Human" or "AI")

    Examples:
        >>> result = is_this_slop("Some text")
        >>> print(result.human_probability)
        0.847
        >>> print(result.ai_probability)
        0.153
        >>> print(result.classification)
        "Human"

        >>> # Use in conditionals
        >>> if result.classification == "AI":
        ...     print(f"Detected slop with {result.ai_probability:.1%} confidence")

        >>> # Check probabilities directly
        >>> if result.ai_probability > 0.8:
        ...     print("High confidence AI-generated")

    """

    __slots__ = ("_inner",)

    def __init__(self, inner: _PredictionResult) -> None:
        """Initialize from Rust PredictionResult.

        Args:
            inner: The underlying Rust PredictionResult object

        """
        self._inner = inner

    @property
    def human_probability(self) -> float:
        """Probability that the text is human-written (0.0 to 1.0)."""
        return self._inner.human_probability

    @property
    def ai_probability(self) -> float:
        """Probability that the text is AI-generated (0.0 to 1.0)."""
        return self._inner.ai_probability

    @property
    def classification(self) -> Literal["Human", "AI"]:
        """Classification label ("Human" or "AI")."""
        return self._inner.classification  # type: ignore[return-value]

    @property
    def num_chunks(self) -> int:
        """Number of text chunks processed (usually 1 for short texts, more for long)."""
        return self._inner.num_chunks

    @property
    def chunk_agreement(self) -> float:
        """Agreement score across chunks (0.5 to 1.0).

        1.0 means all chunks agree on classification.
        0.5 means chunks are evenly split.
        For single-chunk texts, this is always 1.0.
        """
        return self._inner.chunk_agreement

    def __repr__(self) -> str:
        """Return a detailed string representation.

        Returns:
            str: Detailed representation of the prediction

        """
        return self._inner.__repr__()

    def __str__(self) -> str:
        """Return a human-readable string representation.

        Returns:
            str: Human-readable summary of the prediction

        """
        return self._inner.__str__()


def is_this_slop(text: str, threshold: float | None = None) -> Prediction:
    """Predict whether text is AI-generated (slop) or human-written.

    This function analyzes the given text using a trained ML model to determine
    whether it was likely generated by an AI system or written by a human.

    Args:
        text: Input text to classify. Must be a non-empty string.
        threshold: Classification threshold between 0.0 and 1.0 (default: built-in
            threshold optimized for overall f1). If P(AI) >= threshold, the text is classified as AI-generated.
            Lower thresholds are more sensitive (classify more as AI), higher thresholds
            are more conservative (classify more as Human).

    Returns:
        Prediction: A result object containing probabilities and classification.

    Raises:
        ValueError: If text is empty or whitespace-only, or threshold is not in [0, 1].

    Examples:
        >>> result = is_this_slop("This is some text")
        >>> print(result.classification)
        "Human"
        >>> print(f"AI probability: {result.ai_probability:.2%}")
        AI probability: 15.23%

        >>> # Use custom threshold
        >>> result = is_this_slop("Generated content", threshold=0.7)
        >>> if result.classification == "AI":
        ...     print(f"Detected slop with {result.ai_probability:.1%} confidence")

        >>> # Access probabilities directly
        >>> if result.ai_probability > 0.8:
        ...     print("High confidence AI-generated text")

    """
    if not text or not text.strip():
        msg = "Input text must be non-empty"
        raise ValueError(msg)
    if threshold is not None and not 0.0 <= threshold <= 1.0:
        msg = f"threshold must be in [0.0, 1.0], got {threshold}"
        raise ValueError(msg)
    return Prediction(_is_this_slop(text, threshold))


def is_this_slop_batch(texts: list[str], threshold: float | None = None) -> list[Prediction]:
    """Predict whether multiple texts are AI-generated (slop) or human-written.

    Efficiently processes multiple texts in a single batch, which is faster than
    calling is_this_slop() individually for each text.

    Args:
        texts: List of input texts to classify. Must be a non-empty list of strings.
        threshold: Classification threshold between 0.0 and 1.0 (default: built-in
            threshold optimized for overall f1). Applied uniformly to all texts in the batch.

    Returns:
        list[Prediction]: List of prediction results, one for each input text,
            in the same order as the input.

    Raises:
        ValueError: If texts is empty or threshold is not in [0, 1].

    Examples:
        >>> texts = ["First text", "Second text", "Third text"]
        >>> results = is_this_slop_batch(texts)
        >>> for text, result in zip(texts, results):
        ...     print(f"{text}: {result.classification}")
        First text: Human
        Second text: AI
        Third text: Human

        >>> # Count AI-generated texts
        >>> ai_count = sum(1 for r in results if r.classification == "AI")
        >>> print(f"Found {ai_count} slop texts out of {len(texts)}")
        Found 1 slop texts out of 3

        >>> # Filter high-confidence AI texts
        >>> slop = [(text, result) for text, result in zip(texts, results) if result.ai_probability > 0.8]

        >>> # Use custom threshold for entire batch
        >>> conservative_results = is_this_slop_batch(texts, threshold=0.9)

    """
    if not texts:
        msg = "Input texts must be a non-empty list"
        raise ValueError(msg)
    if threshold is not None and not 0.0 <= threshold <= 1.0:
        msg = f"threshold must be in [0.0, 1.0], got {threshold}"
        raise ValueError(msg)
    return [Prediction(r) for r in _is_this_slop_batch(texts, threshold)]


def predict(text: str, threshold: float | None = None) -> Prediction:
    """Alias for [`is_this_slop`].

    Predict whether text is AI-generated (slop) or human-written.

    Args:
        text: Input text to classify. Must be a non-empty string.
        threshold: Classification threshold between 0.0 and 1.0.

    Returns:
        Prediction: A result object containing probabilities and classification.

    Raises:
        ValueError: If text is empty or whitespace-only, or threshold is not in [0, 1].

    """  # noqa: DOC502
    return is_this_slop(text, threshold)


def predict_batch(texts: list[str], threshold: float | None = None) -> list[Prediction]:
    """Alias for [`is_this_slop_batch`].

    Predict whether multiple texts are AI-generated (slop) or human-written.

    Args:
        texts: List of input texts to classify. Must be a non-empty list.
        threshold: Classification threshold between 0.0 and 1.0.

    Returns:
        list[Prediction]: List of prediction results, one for each input text.

    Raises:
        ValueError: If texts is empty or threshold is not in [0, 1].

    """  # noqa: DOC502
    return is_this_slop_batch(texts, threshold)
