name: CI

on:
  push:
    branches: [main, master]
    paths:
      - "python/**"
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/CI.yaml"
  pull_request:

permissions:
  contents: read

env:
  CARGO_PROFILE_TEST_DEBUG: 0
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  rust-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.1

      - name: Check formatting
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets --workspace --features all-testable --locked -- -D warnings
      - name: Run tests
        run: cargo test --all-targets --workspace --features all-testable --locked
      - name: Run docs build
        run: cargo doc --all-features --workspace --no-deps

  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.9.1

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Preprocessing bindings
        working-directory: python/is-it-slop-preprocessing
        run: |
          uv sync --dev --no-install-project -q
          uv run maturin develop --uv -q
          uv run ruff check
          uv run pytest tests/ -q

      - name: Inference bindings
        working-directory: python/is-it-slop
        # env:
        #   RUSTFLAGS: "-C tls-model=global-dynamic"
        run: |
          uv sync --dev --no-install-project -q
          uv run maturin develop --uv -q
          uv run ruff check
          uv run pytest tests/ -q

      - name: Minimize uv cache
        run: uv cache prune --ci
